# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Haris Hardianto
email: ardian.khalil@gmail.com
phone1: +62 856-5956-7750
phone2: +62 822-9879-0019
address: JL.Parungseah No.23 Sukabumi, JawaBarat , Indonesia


description: > # this means to ignore newlines until "baseurl:"
  Haris Hardianto, Sirahanzo, sirahanzo.github.io, PT HARIFF DTE
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  sirahanzo

# Build settings
markdown: kramdown

paginate_path: "/blog/page:num/"

highlighter: rouge

gems:
- jekyll-paginate

paginate: 3



